In [1]:
import pandas as pd

In [2]:
asset_df = pd.read_csv('asset.csv')

In [3]:
asset_df

,asset,capacity,capacity_storage_energy,consumer_balance_sense,discount_rate,economic_lifetime,energy_to_power_ratio,group,investment_integer,investment_integer_storage_energy,...,max_ramp_up,min_operating_point,ramping,storage_method_energy,technical_lifetime,type,unit_commitment,unit_commitment_integer,unit_commitment_method,use_binary_storage_method
0,NL_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,NaN,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN
1,BE_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,NaN,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN
2,DE_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,NaN,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN
3,FR_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,NaN,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN
4,DK_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,NaN,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,BG_Battery,4923.0,14769.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,NaN,NaN,False,1.0,storage,NaN,NaN,NaN,NaN
387,FR_Battery,24461.0,73383.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,NaN,NaN,False,1.0,storage,NaN,NaN,NaN,NaN
388,LV_Battery,149.0,447.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,NaN,NaN,False,1.0,storage,NaN,NaN,NaN,NaN
389,PT_Battery,3294.0,9882.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,NaN,NaN,False,1.0,storage,NaN,NaN,NaN,NaN
390,SK_Battery,2462.0,7386.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,NaN,NaN,False,1.0,storage,NaN,NaN,NaN,NaN

In [4]:
asset_df['start_up_cost'] = 0.0
asset_df['shut_down_cost'] = 0.0

In [5]:
asset_df

,asset,capacity,capacity_storage_energy,consumer_balance_sense,discount_rate,economic_lifetime,energy_to_power_ratio,group,investment_integer,investment_integer_storage_energy,...,ramping,storage_method_energy,technical_lifetime,type,unit_commitment,unit_commitment_integer,unit_commitment_method,use_binary_storage_method,start_up_cost,shut_down_cost
0,NL_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,0.0,0.0
1,BE_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,0.0,0.0
2,DE_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,0.0,0.0
3,FR_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,0.0,0.0
4,DK_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,BG_Battery,4923.0,14769.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,0.0,0.0
387,FR_Battery,24461.0,73383.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,0.0,0.0
388,LV_Battery,149.0,447.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,0.0,0.0
389,PT_Battery,3294.0,9882.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,0.0,0.0
390,SK_Battery,2462.0,7386.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,0.0,0.0

In [6]:
data_df = pd.read_csv('data.csv')

In [7]:
data_df.columns = ['attribute', 'OCGT', 'Gas', 'Coal', 'Lignite', 'Nuclear']

In [8]:
data_df

              attribute  OCGT    Gas    Coal  Lignite  Nuclear
0           max_ramp_up   0.9   0.90   0.500     1.00      0.3
1         max_ramp_down   0.9   0.90   0.500     1.00      0.3
2   ramp_limit_start_up   0.2   0.45   0.380     0.40      0.5
3  ramp_limit_shut_down   0.2   0.45   0.380     0.40      0.5
4              p_min_pu   0.2   0.45   0.325     0.40      0.5
5           min_up_time   NaN   3.00   5.000     7.00      6.0
6         min_down_time   NaN   2.00   6.000     6.00     10.0
7         start_up_cost   9.6  34.20  35.640    19.14     16.5
8        shut_down_cost   0.0   0.00   0.000     0.00      0.0

In [9]:
OCGT_df = asset_df[asset_df['asset'].str.contains('OCGT')]

In [10]:
# 
float(data_df[data_df['attribute'] == 'max_ramp_up']['OCGT'])

0.9

## ADD THE NAMES OF THE PARAMETERS YOU WANT TO INCLUDE IN `params_to_add` IN THE CELL BELOW

In [11]:
dfs_with_data_added = []

params_to_add = ['max_ramp_up', 'max_ramp_down', 'start_up_cost', 'shut_down_cost']
defaults = [0.0, 0.0, 0.0, 0.0]


for asset_type in ['OCGT', 'Gas', 'Coal', 'Nuclear']:
    asset_type_df = asset_df[asset_df['asset'].str.contains(asset_type)]
    for param in params_to_add:
        asset_type_df[param] = float(data_df[data_df['attribute'] == param][asset_type])
        
    dfs_with_data_added.append(asset_type_df)

C:\Users\urosg\AppData\Local\Temp\ipykernel_28968\3350828310.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  asset_type_df[param] = float(data_df[data_df['attribute'] == param][asset_type])

In [12]:
asset_type_dfs_concated_df = pd.concat(dfs_with_data_added, ignore_index=True)

In [13]:
asset_type_dfs_concated_df

,asset,capacity,capacity_storage_energy,consumer_balance_sense,discount_rate,economic_lifetime,energy_to_power_ratio,group,investment_integer,investment_integer_storage_energy,...,ramping,storage_method_energy,technical_lifetime,type,unit_commitment,unit_commitment_integer,unit_commitment_method,use_binary_storage_method,start_up_cost,shut_down_cost
0,NL_OCGT,0.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,9.6,0.0
1,BE_OCGT,244.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,9.6,0.0
2,DE_OCGT,0.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,9.6,0.0
3,FR_OCGT,0.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,9.6,0.0
4,DK_OCGT,612.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,9.6,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,HU_Nuclear,2360.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,16.5,0.0
57,SK_Nuclear,3096.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,16.5,0.0
58,FI_Nuclear,10000.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,16.5,0.0
59,BG_Nuclear,2000.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,16.5,0.0
60,RO_Nuclear,3087.0,0.0,NaN,0.0,1.0,0,NaN,False,False,...,True,False,1.0,producer,True,True,basic,NaN,16.5,0.0

In [14]:
asset_type_dfs_concated_df['unit_commitment'] = 'true'
asset_type_dfs_concated_df['unit_commitment_integer'] = 'true'
asset_type_dfs_concated_df['unit_commitment_method'] = 'basic'
asset_type_dfs_concated_df['ramping'] = 'true'
asset_type_dfs_concated_df['min_operating_point'] = 0.25

In [15]:
asset_type_dfs_concated_df['unit_commitment_method']

0     basic
1     basic
2     basic
3     basic
4     basic
      ...
56    basic
57    basic
58    basic
59    basic
60    basic
Name: unit_commitment_method, Length: 61, dtype: object

In [16]:
merged = asset_df.merge(asset_type_dfs_concated_df[['asset', *params_to_add, 'unit_commitment', 'unit_commitment_integer', 'unit_commitment_method', 'ramping', 'min_operating_point']], on='asset', how='left', suffixes=('', '_y'))

for (param, default) in zip(params_to_add, defaults):
    merged[param] = merged[f'{param}_y']

    merged = merged.drop(columns=[f'{param}_y'])
    
#     merged[param] = merged[param].fillna(default)
    
    
for param in ['unit_commitment', 'unit_commitment_integer', 'unit_commitment_method', 'ramping', 'min_operating_point']:
    merged[param] = merged[f'{param}_y']

    merged = merged.drop(columns=[f'{param}_y'])

In [17]:
merged

,asset,capacity,capacity_storage_energy,consumer_balance_sense,discount_rate,economic_lifetime,energy_to_power_ratio,group,investment_integer,investment_integer_storage_energy,...,ramping,storage_method_energy,technical_lifetime,type,unit_commitment,unit_commitment_integer,unit_commitment_method,use_binary_storage_method,start_up_cost,shut_down_cost
0,NL_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,NaN,NaN
1,BE_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,NaN,NaN
2,DE_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,NaN,NaN
3,FR_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,NaN,NaN
4,DK_E_Demand,0.0,0.0,>=,0.0,1.0,0,NaN,False,False,...,NaN,False,1.0,consumer,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,BG_Battery,4923.0,14769.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,NaN,NaN
387,FR_Battery,24461.0,73383.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,NaN,NaN
388,LV_Battery,149.0,447.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,NaN,NaN
389,PT_Battery,3294.0,9882.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,NaN,NaN
390,SK_Battery,2462.0,7386.0,NaN,0.0,1.0,0,NaN,True,False,...,NaN,False,1.0,storage,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
merged['max_ramp_down'].unique()

array([nan, 0.9, 0.5, 0.3])

In [19]:
merged = merged.applymap(lambda x: str(x).lower() if isinstance(x, bool) else x)

In [20]:
merged.to_csv('asset-UC-added.csv', index=False)